import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Flex, Box, Link } from "@chakra-ui/react";

import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box
            as="header"
            minHeight="40px"
            width="100%"
            borderBottom="1px solid black"
            display="flex"
            justifyContent="space-between"
            alignItems="center"
            padding="0 20px"
          >
            <Box as="h1">Posts list</Box>
            <Box as="h1">
              <Link
                href="https://github.com/MickKrishtopa/next-js-posts"
                target="blank"
              >
                Repo
              </Link>
            </Box>
          </Box>
          <Box as="main" padding="0 20px" flex="1 0 auto">
            {children}
          </Box>
          <Box
            as="footer"
            minHeight="40px"
            width="100%"
            borderTop="1px solid black"
            display="flex"
            justifyContent="space-between"
            alignItems="center"
            padding="0 20px"
          >
            <Box as="h1">Posts list</Box>
            <Box as="h1">
              <Link
                href="https://github.com/MickKrishtopa/next-js-posts"
                target="blank"
              >
                Repo
              </Link>
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}

